build_macosx:
  stage: build
  tags:
    - mac
    - build
  before_script:
    - brew update
    - brew upgrade
  script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_INSTALL_PREFIX=/usr/local -DENABLE_STATIC=1 -DENABLE_OPENCV=1 -DENABLE_SERIALDEV=1 -DEXAMPLES_INSTALL=1 ..
    - make -j2
    - sudo make install

build_raspbian:
  stage: build
  tags:
    - rpi
    - build
  before_script:
    - sudo apt-get -y update
    - sudo apt-get -y upgrade
  script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_INSTALL_PREFIX=/usr -DENABLE_STATIC=1 -DENABLE_OPENCV=1 -DENABLE_SERIALDEV=1 -DEXAMPLES_INSTALL=1 ..
    - make -j2
    - sudo make install

build_ubuntu1804:
  stage: build
  tags:
    - docker
    - build
  image: ubuntu:18.04
  before_script:
    - apt-get -y update
    - apt-get -y upgrade
    - apt-get -y install build-essential cmake pkg-config libusb-1.0-0-dev libserialport-dev libopencv-dev
  script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_INSTALL_PREFIX=/usr -DENABLE_STATIC=1 -DENABLE_OPENCV=1 -DENABLE_SERIALDEV=1 -DEXAMPLES_INSTALL=1 ..
    - make -j2
