stages:
  - build

build_mac:
  stage: build
  tags:
    - mac
    - build
  script:
    - cmake -DCMAKE_INSTALL_PREFIX=/usr/local -DENABLE_OPENCV=1 .
    - make -j2

 build_rpi:
  stage: build
  tags:
    - rpi
    - build
  script:
    - cmake -DCMAKE_INSTALL_PREFIX=/usr .
    - make -j2
