build_macosx:
  stage: build
  tags:
    - macosx
    - build
  before_script:
    - brew update
    - brew upgrade
  script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_INSTALL_PREFIX=/usr/local -DENABLE_STATIC=1 -DENABLE_OPENCV=1 -DENABLE_SERIALDEV=1 -DEXAMPLES_INSTALL=1 ..
    - make -j1
    - if [[ "${CI_COMMIT_REF_NAME}" == "master" ]] ; then sudo make install; fi

build_windows:
  stage: build
  tags:
    - windows
    - build
  variables:
    MSYSTEM: MINGW64
  before_script:
    - pacman -Syuu --noconfirm
  script:
    - source /usr/bin/init-paths
    - mkdir build
    - cd build
    - cmake -G "MSYS Makefiles" -DCMAKE_INSTALL_PREFIX=/mingw64 -DENABLE_STATIC=1 -DENABLE_OPENCV=1 -DENABLE_SERIALDEV=1 -DEXAMPLES_INSTALL=1 ..
    - make -j1
    - if [[ "${CI_COMMIT_REF_NAME}" == "master" ]] ; then make install; fi

build_raspbian:
  stage: build
  tags:
    - raspbian
    - build
  before_script:
    - sudo apt-get -y update
    - sudo apt-get -y upgrade
  script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_INSTALL_PREFIX=/usr -DENABLE_STATIC=1 -DENABLE_OPENCV=1 -DENABLE_SERIALDEV=1 -DEXAMPLES_INSTALL=1 ..
    - make -j1
    - if [[ "${CI_COMMIT_REF_NAME}" == "master" ]] ; then sudo make install; fi

build_ubuntu_1604:
  stage: build
  tags:
    - docker
  image: inivation/ubuntu:16.04
  before_script:
    - apt-get -y update
    - apt-get -y upgrade
  script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_C_COMPILER=gcc-7 -DCMAKE_CXX_COMPILER=g++-7 -DCMAKE_INSTALL_PREFIX=/usr -DENABLE_STATIC=1 -DENABLE_OPENCV=1 -DENABLE_SERIALDEV=0 -DEXAMPLES_INSTALL=1 ..
    - make -j1

build_ubuntu_1804:
  stage: build
  tags:
    - docker
  image: inivation/ubuntu:18.04
  before_script:
    - apt-get -y update
    - apt-get -y upgrade
  script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_INSTALL_PREFIX=/usr -DENABLE_STATIC=1 -DENABLE_OPENCV=1 -DENABLE_SERIALDEV=1 -DEXAMPLES_INSTALL=1 ..
    - make -j1

build_ubuntu_curr_gcc6:
  stage: build
  tags:
    - docker
  image: inivation/ubuntu:rolling
  before_script:
    - apt-get -y update
    - apt-get -y upgrade
  script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_C_COMPILER=gcc-6 -DCMAKE_CXX_COMPILER=g++-6 -DCMAKE_INSTALL_PREFIX=/usr -DENABLE_STATIC=1 -DENABLE_OPENCV=1 -DENABLE_SERIALDEV=1 -DEXAMPLES_INSTALL=1 ..
    - make -j1

build_ubuntu_curr_gcc7:
  stage: build
  tags:
    - docker
  image: inivation/ubuntu:rolling
  before_script:
    - apt-get -y update
    - apt-get -y upgrade
  script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_C_COMPILER=gcc-7 -DCMAKE_CXX_COMPILER=g++-7 -DCMAKE_INSTALL_PREFIX=/usr -DENABLE_STATIC=1 -DENABLE_OPENCV=1 -DENABLE_SERIALDEV=1 -DEXAMPLES_INSTALL=1 ..
    - make -j1

build_ubuntu_curr_gcc8:
  stage: build
  tags:
    - docker
  image: inivation/ubuntu:rolling
  before_script:
    - apt-get -y update
    - apt-get -y upgrade
  script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_C_COMPILER=gcc-8 -DCMAKE_CXX_COMPILER=g++-8 -DCMAKE_INSTALL_PREFIX=/usr -DENABLE_STATIC=1 -DENABLE_OPENCV=1 -DENABLE_SERIALDEV=1 -DEXAMPLES_INSTALL=1 ..
    - make -j1

build_ubuntu_curr_gcc9:
  stage: build
  tags:
    - docker
  image: inivation/ubuntu:rolling
  before_script:
    - apt-get -y update
    - apt-get -y upgrade
  script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_C_COMPILER=gcc-9 -DCMAKE_CXX_COMPILER=g++-9 -DCMAKE_INSTALL_PREFIX=/usr -DENABLE_STATIC=1 -DENABLE_OPENCV=1 -DENABLE_SERIALDEV=1 -DEXAMPLES_INSTALL=1 ..
    - make -j1

build_ubuntu_curr_clang6:
  stage: build
  tags:
    - docker
  image: inivation/ubuntu:rolling
  before_script:
    - apt-get -y update
    - apt-get -y upgrade
  script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_C_COMPILER=clang-6.0 -DCMAKE_CXX_COMPILER=clang++-6.0 -DCMAKE_INSTALL_PREFIX=/usr -DENABLE_STATIC=1 -DENABLE_OPENCV=1 -DENABLE_SERIALDEV=1 -DEXAMPLES_INSTALL=1 ..
    - make -j1

build_ubuntu_curr_clang7:
  stage: build
  tags:
    - docker
  image: inivation/ubuntu:rolling
  before_script:
    - apt-get -y update
    - apt-get -y upgrade
  script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_C_COMPILER=clang-7 -DCMAKE_CXX_COMPILER=clang++-7 -DCMAKE_INSTALL_PREFIX=/usr -DENABLE_STATIC=1 -DENABLE_OPENCV=1 -DENABLE_SERIALDEV=1 -DEXAMPLES_INSTALL=1 ..
    - make -j1

build_ubuntu_curr_clang8:
  stage: build
  tags:
    - docker
  image: inivation/ubuntu:rolling
  before_script:
    - apt-get -y update
    - apt-get -y upgrade
  script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_C_COMPILER=clang-8 -DCMAKE_CXX_COMPILER=clang++-8 -DCMAKE_INSTALL_PREFIX=/usr -DENABLE_STATIC=1 -DENABLE_OPENCV=1 -DENABLE_SERIALDEV=1 -DEXAMPLES_INSTALL=1 ..
    - make -j1

pages:
  tags:
    - docker
  image: inivation/ubuntu:rolling
  script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_INSTALL_PREFIX=/usr -DENABLE_OPENCV=1 -DENABLE_SERIALDEV=1 ..
    - make doc
    - cd ..
    - mv build/docs/html public
  artifacts:
    paths:
      - public
  only:
    - master
