build_mac:
  stage: build
  tags:
    - mac
    - build
  before_script:
    - brew update
    - brew upgrade
  script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_INSTALL_PREFIX=/usr/local -DENABLE_STATIC=1 -DENABLE_OPENCV=1 -DENABLE_SERIALDEV=1 -DEXAMPLES_INSTALL=1 ..
    - make -j2
    - sudo make install

build_rpi:
  stage: build
  tags:
    - rpi
    - build
  before_script:
    - sudo apt-get -y update
    - sudo apt-get -y upgrade
  script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_INSTALL_PREFIX=/usr -DENABLE_STATIC=1 -DENABLE_OPENCV=1 -DENABLE_SERIALDEV=1 -DEXAMPLES_INSTALL=1 ..
    - make -j2
    - sudo make install
